var localConfig = {
	languages : {
		"zh" : {
			//tool bar
			toolBar_save 			: "保存",
			toolBar_import 			: "导入幻灯片文件",
			toolBar_openFileSystem 	: "打开保存文件保存目录",
			toolBar_preview 		: "预览",
			toolBar_setAnimation 	: "更改幻灯片过渡动画",
			toolBar_addVideo 		: "添加视频(暂时只支持Mmp4格式)",
			toolBar_addImage 		: "插入一张图片",
			toolBar_addText 		: "插入文本输入框",
			toolBar_addCode 		: "插入代码编辑框",
			toolBar_changeScale		: "更改幻灯片分辨率比例",
			toolBar_help : '帮助',
			//animation
			anim_slider 			: "幻灯片",
			anim_sliderZoom 		: "放大幻灯片",
			anim_rotateLeft 		: "向左旋转",
			anim_rotateRight 		: "向右旋转",
			anim_reverse 			: "垂直翻转",
			anim_label				: "过渡动画",
			// shape bar
			shape_triangle : "插入三角形",
			shape_circular : "插入圆形",
			shape_rectangle : "插入矩形",
			shape_heart : "插入心形",
			shape_star : "插入星形",
			shape_message : "插入消息框图形",
			shape_moon : "插入月牙形",
			shape_polygon : "插入多角形",
			shape_doodle : "插入自定义图形",
			//canvas menu
			canvasMenu_delete : "删除",
			canvasMenu_copy : "复制",
			canvasMenu_cut : "剪切",
			canvasMenu_paste : "粘贴",
			canvasMenu_layerForward : '上移一层',
			canvasMenu_layerBackward : '下移一层',
			canvasMenu_layerFont : '置顶',
			canvasMenu_layerBack : '置底',
			canvasMenu_background : '背景',
			canvasMenu_settings : '属性',
			viewMenu_create : '新建',
			viewMenu_insert : '插入',
			viewMenu_delete : '删除',
			settings_background : "背景设置",
			settings_border : "边框设置",
			settings_shadow : "内阴影",
			settings_transform : "变换",
			settings_title_bgColor : '背景色',
			settings_item_red : '红',
			settings_item_green : '绿',
			settings_item_blue : '蓝',
			settings_title_bgAttribute : '背景属性',
			settings_item_bgColor : '背景色',
			settings_item_opacity : '透明度',
			settings_item_fontSize : '字体大小',
			settings_title_borderAttribute : '边框属性',
			settings_item_borderWidth : '宽带',
			settings_item_borderType : '类型',
			border_none : '无',
			border_solid : '实线',
			border_dashed : '折线',
			border_double : '双实线',
			border_dotted : '虚线',
			border_groove : '3D凹槽',
			border_inset : '3D凹边',
			border_outset : '3D凸边',
			border_ridge : '菱形边',
			settings_title_bdrAttribute : '圆角',
			settings_item_leftTop : '左上圆角',
			settings_item_leftBottom : '左下圆角',
			settings_item_rightBottom : '右下圆角',
			settings_item_rightTop : '右上圆角',
			fileSystem_newFolder : "创建目录",
			fileSystem_saveAs : "另存为",
			fileSystem_notice_restore : "正在恢复上次打开文件",
			//buttons
			btn_close : '关闭'
		},
		'en' : {
			//tool bar
			toolBar_save 			: "save file",
			toolBar_import 			: "import file",
			toolBar_openFileSystem 	: "open storage filesystem",
			toolBar_preview 		: "current presentation preview",
			toolBar_setAnimation 	: "set frame transition animation",
			toolBar_addVideo 		: "add a video element",
			toolBar_addImage 		: "add an image element",
			toolBar_addText 		: "add a text-box element",
			toolBar_addCode 		: "add a high-light editor element",
			toolBar_changeScale 	: "change current presentation screen size",
			toolBar_help 			: 'intro-helping',
			// animation
			anim_slider 			: "slider",
			anim_sliderZoom 		: "slider zoom",
			anim_rotateLeft 		: "rotate left",
			anim_rotateRight 		: "rotate right",
			anim_reverse 			: "reverse",
			anim_label				: "transition",
			// shape bar
			shape_triangle : "insert triangle shape",
			shape_circular : "insert circular shape",
			shape_rectangle : "insert rectangle shape",
			shape_heart : "insert heart shape",
			shape_star : "insert star shape",
			shape_message : "insert message shape",
			shape_moon : "insert moon shape",
			shape_polygon : "insert polygon shape",
			shape_doodle : "insert custom doodle",
			//canvas menu
			canvasMenu_delete : "Delete",
			canvasMenu_copy : "Copy",
			canvasMenu_cut : "Cut",
			canvasMenu_paste : "Paste",
			canvasMenu_layerForward : 'Layer forward',
			canvasMenu_layerBackward : 'Layer backward',
			canvasMenu_layerFont : 'Layer to font',
			canvasMenu_layerBack : 'Layer to back',
			canvasMenu_background : 'background',
			canvasMenu_settings : 'settings',
			viewMenu_create : 'create',
			viewMenu_insert : 'insert',
			viewMenu_delete : 'delete',
			settings_background : "Background",
			settings_border : "Border",
			settings_shadow : "Shadow",
			settings_transform : "Transform",
			settings_title_bgColor : 'Background Color',
			settings_item_red : 'Red',
			settings_item_green : 'Green',
			settings_item_blue : 'Blue',
			settings_title_bgAttribute : 'Background Attributes',
			settings_item_bgColor : 'Enable Background Color',
			settings_item_opacity : 'Opacity',
			settings_item_fontSize : 'Font Size',
			settings_title_borderAttribute : 'Border',
			settings_item_borderWidth : 'Width',
			settings_item_borderType : 'Type',
			border_none : 'none',
			border_solid : 'solid',
			border_dashed : 'dashed',
			border_double : 'double',
			border_dotted : 'dotted',
			border_groove : 'groove',
			border_inset : 'inset',
			border_outset : 'outset',
			border_ridge : 'ridge',
			settings_title_bdrAttribute : 'Border Radius',
			settings_item_leftTop : 'Left Top',
			settings_item_leftBottom : 'Left Bottom',
			settings_item_rightBottom : 'Right Bottom',
			settings_item_rightTop : 'Right Top',
			fileSystem_newFolder : "New Folder",
			fileSystem_saveAs : "Save As",
			fileSystem_notice_restore : "Loading file, please wait...",
			//buttons
			btn_close : 'close'
		}
	}
}